openapi: 3.0.1
info:
  title: Miliare CRM API
  version: 1.0.0
  description: |
    Legacy REST API for managing user profiles, partners, customers and referrals.
    The application now uses Amplify's GraphQL API and Storage for current operations.
    Because the backend is implemented with Amplify Gen 2, this specification remains for historical reference only.
paths:
  /profiles/{userId}:
    get:
      summary: Get user profile
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: User profile
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile'
    put:
      summary: Update user profile
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserProfile'
      responses:
        '200':
          description: Updated
  /partners:
    post:
      summary: Create partner
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Partner'
      responses:
        '201':
          description: Created
    get:
      summary: List partners
      responses:
        '200':
          description: Partner list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Partner'
  /partners/{partnerId}:
    get:
      summary: Get partner
      parameters:
        - name: partnerId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Partner
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Partner'
    put:
      summary: Update partner
      parameters:
        - name: partnerId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Partner'
      responses:
        '200':
          description: Updated
  /customers:
    post:
      summary: Create customer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Customer'
      responses:
        '201':
          description: Created
    get:
      summary: List customers
      responses:
        '200':
          description: Customer list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Customer'
  /customers/{customerId}:
    get:
      summary: Get customer
      parameters:
        - name: customerId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Customer
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
    put:
      summary: Update customer
      parameters:
        - name: customerId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Customer'
      responses:
        '200':
          description: Updated
  /referrals:
    post:
      summary: Create referral
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Referral'
      responses:
        '201':
          description: Created
    get:
      summary: List referrals
      responses:
        '200':
          description: Referral list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Referral'
  /referrals/{referralId}:
    get:
      summary: Get referral
      parameters:
        - name: referralId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Referral
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Referral'
    put:
      summary: Update referral
      parameters:
        - name: referralId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Referral'
      responses:
        '200':
          description: Updated
components:
  schemas:
    UserProfile:
      type: object
      properties:
        userId:
          type: string
        profileType:
          type: string
        email:
          type: string
        data:
          type: object
          additionalProperties: true
    Partner:
      type: object
      properties:
        partnerId:
          type: string
        name:
          type: string
        email:
          type: string
        status:
          type: string
    Customer:
      type: object
      properties:
        customerId:
          type: string
        name:
          type: string
        email:
          type: string
    Referral:
      type: object
      properties:
        referralId:
          type: string
        userId:
          type: string
        customerId:
          type: string
        status:
          type: string
